### ISSUE TITLE
Wiki Home Page - Due 6/9

### ISSUE THREAD

**Issue by cjc473** [laurencary/Slaque#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a description sentence of the app
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

**Comment by cjc473** [comment]
This looks good! Under the description of the website, add the following line:

`# Slaque Design Documents`

**Comment by laurencary** [comment]
@cjc473  Added!

**Comment by cjc473** [comment]
Done!
