### ISSUE TITLE
Sample State - Due 6/12

### ISSUE THREAD

**Issue by cjc473** [laurencary/Slaque#4]
# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + The author username and imageurl for a post. Basically any info that the user can't change
        + Like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by laurencary** [comment]
Just a heads up, I made the changes to the schema & sample state. I'm now referring to users as a single person login in, and the workspaceUser is the profile associated with that workspace.

**Comment by cjc473** [comment]
This looks good and I can see you put a lot of thought into this. The Session reducer is atypical and does have a little nesting, but if you are only looking at workspaces in context of the current user, then this should be fine. If you decide you need to refactor it later, you can always create a distinct workplaces slice of state.

Done!

**Comment by laurencary** [comment]
Oh I appreciate that feedback - I made a currentWorkspace, a workspaces state, and set the session state to just the current user.

Maybe I don't need the currentWorkspace? maybe that can all just be handled in the components. But I would want the currentWorkspaceUserId pretty accessible
