### ISSUE TITLE
Frontend Routes - Due 6/13

### ISSUE THREAD

**Issue by cjc473** [laurencary/Slaque#6]
# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by cjc473** [comment]
This is basically finished. The one change is to remove the #'s from the urls. Those probably appear in the real slack if they use a hash router, but since we're using a browser router we will not have #'s in our routes.

**Comment by laurencary** [comment]
Ah interesting - I removed them!

**Comment by cjc473** [comment]
Done!
